# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
selene = "kampfkarren/selene@0.29.0"
stylua = "johnnymorganz/stylua@2.1.0"
wally = "upliftgames/wally@0.3.2"
